// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZlEdEQwG-YgpbsgFXZjjCgdhoJF5IZVw',
    appId: '1:704660588087:web:c3cf7203e37ed00365a1b2',
    messagingSenderId: '704660588087',
    projectId: 'gerador-de-senha-a4cb8',
    authDomain: 'gerador-de-senha-a4cb8.firebaseapp.com',
    storageBucket: 'gerador-de-senha-a4cb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZlEdEQwG-YgpbsgFXZjjCgdhoJF5IZVw',
    appId: '1:704660588087:android:c3cf7203e37ed00365a1b2',
    messagingSenderId: '704660588087',
    projectId: 'gerador-de-senha-a4cb8',
    storageBucket: 'gerador-de-senha-a4cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZlEdEQwG-YgpbsgFXZjjCgdhoJF5IZVw',
    appId: '1:704660588087:ios:c3cf7203e37ed00365a1b2',
    messagingSenderId: '704660588087',
    projectId: 'gerador-de-senha-a4cb8',
    storageBucket: 'gerador-de-senha-a4cb8.firebasestorage.app',
    iosBundleId: 'com.example.geradorDeSenha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZlEdEQwG-YgpbsgFXZjjCgdhoJF5IZVw',
    appId: '1:704660588087:ios:c3cf7203e37ed00365a1b2',
    messagingSenderId: '704660588087',
    projectId: 'gerador-de-senha-a4cb8',
    storageBucket: 'gerador-de-senha-a4cb8.firebasestorage.app',
    iosBundleId: 'com.example.geradorDeSenha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZlEdEQwG-YgpbsgFXZjjCgdhoJF5IZVw',
    appId: '1:704660588087:web:c3cf7203e37ed00365a1b2',
    messagingSenderId: '704660588087',
    projectId: 'gerador-de-senha-a4cb8',
    authDomain: 'gerador-de-senha-a4cb8.firebaseapp.com',
    storageBucket: 'gerador-de-senha-a4cb8.firebasestorage.app',
  );
}
